# ===PLUGINS===
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'

# ===OPTIONS===
# Prevent clipboard permission modal from appearing
set -s set-clipboard on

set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g status-bg green

# set -g mouse on

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Ensure we use fish
run-shell '([ "$(uname)" = "Darwin" ] && echo "set-option -g default-command \"reattach-to-user-namespace -l $(which fish)\"" || echo "set-option -g default-shell $(which fish)")  > ~/.tmp && tmux source-file ~/.tmp && rm ~/.tmp'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
